In [3]:
import tensorflow as tf
print(tf.constant([[1,2,3],[4,5,6]])) #matrix
print(tf.constant([42])) #scalar

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor([42], shape=(1,), dtype=int32)


In [5]:
t=tf.constant([[1,2,3],[4,5,6]])
print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'int32'>


In [11]:
print(t[:,1:])
print(t[...,1,tf.newaxis])

tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2]
 [5]], shape=(2, 1), dtype=int32)


In [10]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a[:,1,np.newaxis])
print(a[...,1,np.newaxis])

[[2]
 [5]]
[[2]
 [5]]


In [12]:
t+10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [13]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [14]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>