In [74]:
import tensorflow as tf
print(tf.constant([[1,2,3],[4,5,6]])) #matrix
print(tf.constant([42])) #scalar

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor([42], shape=(1,), dtype=int32)


In [75]:
t=tf.constant([[1,2,3],[4,5,6]])
print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'int32'>


In [76]:
print(t[:,1:])
print(t[...,1,tf.newaxis])

tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2]
 [5]], shape=(2, 1), dtype=int32)


In [77]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a[:,1,np.newaxis])
print(a[...,1,np.newaxis])

[[2]
 [5]]
[[2]
 [5]]


In [78]:
t+10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [79]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [80]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [81]:
### Tensors and Numpy

a = np.array([2,3,4])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 3, 4])>

In [82]:
t.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [83]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 4,  9, 16])>

In [84]:
np.square(t)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [85]:
tf.constant(2.)+tf.constant(40)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]

In [15]:
t2=tf.constant(40,dtype=tf.float64)
tf.constant(2.)+tf.cast(t2,tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [16]:
### variables
v = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
print(v)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>


In [97]:
v.assign(2*v)
v[0,1].assign(42)
v[:,2].assign([0.,1.])
print(v.shape)
v.scatter_nd_update(indices=[[1,1]],updates=[200])
v.scatter_nd_update(indices=[[0,0],[0,1]],updates=[100,200])

(2, 3)


<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[1.000000e+02, 2.000000e+02, 0.000000e+00],
       [4.194304e+06, 2.000000e+02, 1.000000e+00]], dtype=float32)>