In [1]:
import numpy as np
import random

class Conv3x3:
    #a convolutin layer using 3x3 filters

    def __init__(self, num_filters):
        self.num_filters = num_filters
        #filter initialization
        self.filters = np.random.randn(num_filters,3,3) / 9
    
    '''
    
    '''
    def iterate_(self, image):
        row, col = image.shape
        #conv layers and output layer initialization
        self.layer = np.zeros(())

        for i in range(row):
            for j in range(col):
                if i <= row-2 and j <= col-2: 
                    roi = image[i:(i+3),j:(j+3)]
                    yield roi, i, j
    
    def forward(self, image):
        row, col = image.shape
        #conv layers and output layer initialization
        self.layer = np.zeros((self.num_filters, row-2, col-2))

        for 
        


In [4]:
layer1 = Conv3x3(2)
layer1.filters

array([[[-0.05029708,  0.14375138, -0.11783392],
        [ 0.08655909,  0.00107742, -0.10752458],
        [-0.02741327, -0.05431828,  0.07293011]],

       [[ 0.04597768,  0.14104938,  0.04242207],
        [-0.0835017 , -0.07000422, -0.01668593],
        [ 0.24044777,  0.068398  ,  0.19535085]]])

In [31]:
class Conv3x3:
  def __init__(self, num_filters):
    self.num_filters = num_filters

    # filters is a 3d array with dimensions (num_filters, 3, 3)
    # We divide by 9 to reduce the variance of our initial values
    self.filters = np.random.randn(num_filters, 3, 3) / 9

  def iterate_regions(self, image):
    '''
    Generates all possible 3x3 image regions using valid padding.
    - image is a 2d numpy array
    '''
    h, w = image.shape

    for i in range(h - 2):
      for j in range(w - 2):
        im_region = image[i:(i + 3), j:(j + 3)]
        yield im_region, i, j

  def forward(self, input):
    '''
    Performs a forward pass of the conv layer using the given input.
    Returns a 3d numpy array with dimensions (h, w, num_filters).
    - input is a 2d numpy array
    '''
    h, w = input.shape
    output = np.zeros((h - 2, w - 2, self.num_filters))

    for im_region, i, j in self.iterate_regions(input):
        # print(im_region * self.filters)
        # if i == 1 and j == 1:
            # print(im_region)
            # print(self.filters)
            # print(im_region*self.filters)
        output[i, j] = np.sum(im_region * self.filters, axis=(1, 2))
        # print(output[i,j])

    return output

In [23]:
from tensorflow.keras import datasets, layers, models
import keras
import tensorflow as tf

In [24]:
((train_data, train_labels),
 (test_data, test_labels)) = tf.keras.datasets.fashion_mnist.load_data()

In [32]:
conv = Conv3x3(8)
output = conv.forward(train_data[0])
print(conv.filters)
print(output.shape)
# print(output[:,:,0])

[[[-0.09115222 -0.08159382  0.01271225]
  [ 0.1046643  -0.04405305 -0.04051145]
  [ 0.03407765 -0.08261454 -0.11673225]]

 [[ 0.22740578 -0.0221493  -0.04868169]
  [ 0.04169566  0.09517268  0.08993991]
  [ 0.06939456  0.06513999 -0.0624412 ]]

 [[-0.00694448 -0.06249955  0.06541286]
  [ 0.12945537 -0.04102092  0.03470676]
  [-0.07053104  0.09874111 -0.0642567 ]]

 [[ 0.07371908  0.05209876 -0.1223342 ]
  [ 0.05579584 -0.15541291  0.00519382]
  [-0.04482362  0.0463572  -0.20468027]]

 [[-0.04004651 -0.01277632  0.07887955]
  [ 0.08284219 -0.02909077  0.00845005]
  [-0.06389636  0.0347158  -0.03648007]]

 [[-0.13550921  0.0501109   0.01194215]
  [ 0.1709952   0.00331749 -0.20508699]
  [-0.13600515 -0.32061486  0.17775934]]

 [[-0.18098278  0.01637528  0.04754196]
  [ 0.10250239  0.07659441  0.13520239]
  [-0.08029963  0.09910694  0.14444742]]

 [[ 0.11386419  0.06516792 -0.14464417]
  [ 0.17187195  0.0847667  -0.2228127 ]
  [-0.15062255 -0.04257993  0.09375307]]]
(26, 26, 8)
